#MediationZone Export
#Sun Jul 12 14:09:03 GST 2026
mzexport.mzname=DR
mzexport.mzdetailedversion=9.3.0.2
mzexport.hostname=saps4hana
Configuration/SAPCM-BATCH3_SFTP/Workflow/SAPCM-BATCH3_SFTP.WFL_SFTP_COLL_dependencies=System/Access Group/ZSAP_CM_ALL,System/User/sapcmuser14
mzexport.creation=1783850943372
Configuration/SAPCM-BATCH3_SFTP/Ultra\ Format/SAPCM-BATCH3_SFTP.UFL_SFTP_dependencies=System/Access Group/ZSAP_CM_ALL,System/User/sapcmuser14
mzexport.username=sapcmuser14
mzexport.mzrepository=tag-mz-9.3.0.2-RC0-16-g830dc5b
mzexport.mzversion=9.3.0.2
Configuration/SAPCM-BATCH3_SFTP/Workflow/SAPCM-BATCH3_SFTP.WFL_SFTP_COLL=SAPCM-BATCH3_SFTP.WFL_SFTP_COLL
Configuration/SAPCM-BATCH3_SFTP/Workflow_order=Configuration/SAPCM-BATCH3_SFTP/Workflow/SAPCM-BATCH3_SFTP.WFL_SFTP_COLL
Configuration/SAPCM-BATCH3_SFTP/Ultra\ Format/SAPCM-BATCH3_SFTP.UFL_SFTP=SAPCM-BATCH3_SFTP.UFL_SFTP
Configuration/SAPCM-BATCH3_SFTP/Ultra\ Format_order=Configuration/SAPCM-BATCH3_SFTP/Ultra Format/SAPCM-BATCH3_SFTP.UFL_SFTP
