#MediationZone Export
#Sun Jul 12 13:31:59 IST 2026
mzexport.mzname=DR
mzexport.mzdetailedversion=9.3.0.2
mzexport.hostname=localhost.localdomain
mzexport.mzrepository=tag-mz-9.3.0.2-RC0-16-g830dc5b
Configuration/List/Ultra\ Format/List.UFL_ListDecode=List.UFL_ListDecode
mzexport.creation=1783843319510
mzexport.mzversion=9.3.0.2
Configuration/List/Ultra\ Format_order=Configuration/List/Ultra Format/List.UFL_ListDecode
mzexport.username=Jai K
