#MediationZone Export
#Sun Jul 12 13:48:59 GST 2026
mzexport.mzname=DR
mzexport.mzdetailedversion=9.3.0.2
mzexport.hostname=saps4hana
Configuration/SAPCM-BATCH3_SFTP/Workflow/SAPCM-BATCH3_SFTP.WFL_SFTP_COLL_dependencies=System/Access Group/ZSAP_CM_ALL,System/User/sapcmuser14
mzexport.mzrepository=tag-mz-9.3.0.2-RC0-16-g830dc5b
mzexport.creation=1783849739857
mzexport.mzversion=9.3.0.2
Configuration/SAPCM-BATCH3_SFTP/Workflow/SAPCM-BATCH3_SFTP.WFL_SFTP_COLL=SAPCM-BATCH3_SFTP.WFL_SFTP_COLL
Configuration/SAPCM-BATCH3_SFTP/Workflow_order=Configuration/SAPCM-BATCH3_SFTP/Workflow/SAPCM-BATCH3_SFTP.WFL_SFTP_COLL
mzexport.username=sapcmuser14
