#MediationZone Export
#Sun Jul 12 13:02:20 IST 2026
mzexport.mzname=DR
mzexport.mzdetailedversion=9.3.0.2
mzexport.hostname=localhost.localdomain
Configuration/List/Workflow_order=Configuration/List/Workflow/List.WFL_List1
mzexport.creation=1783841539774
mzexport.username=mzadmin
Configuration/List/Ultra\ Format/List.UFL_ListUseCase1=List.UFL_ListUseCase1
Configuration/List/Workflow/List.WFL_List1_dependencies=Configuration/List/Ultra Format/List.UFL_ListUseCase1
mzexport.mzrepository=tag-mz-9.3.0.2-RC0-16-g830dc5b
Configuration/List/Ultra\ Format/List.UFL_ListDecode=List.UFL_ListDecode
mzexport.mzversion=9.3.0.2
Configuration/List/Workflow/List.WFL_List1=List.WFL_List1
Configuration/List/Ultra\ Format_order=Configuration/List/Ultra Format/List.UFL_ListDecode,Configuration/List/Ultra Format/List.UFL_ListUseCase1
